platform :osx, '12.3'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
    target.build_configurations.each do |config|
      # Remove invalid Metal toolchain search path to silence ld warnings
      paths = config.build_settings['LIBRARY_SEARCH_PATHS'] || []
      if paths.is_a?(Array)
        config.build_settings['LIBRARY_SEARCH_PATHS'] = paths.reject { |p| p.to_s.include?('Metal.xctoolchain') || p.to_s.include?('cryptexd') }
      end
      # Bump deployment target for pods that set it below supported minimum (10.13)
      if config.build_settings['MACOSX_DEPLOYMENT_TARGET'].to_f < 10.13
        config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.13'
      end
      # Silence deprecation warnings from geolocator_apple (CLLocationManager authorizationStatus etc.)
      if target.name.include?('geolocator_apple')
        config.build_settings['GCC_WARN_DEPRECATED_FUNCTIONS'] = 'NO'
        flags = config.build_settings['OTHER_CFLAGS'] || []
        flags = [flags] unless flags.is_a?(Array)
        config.build_settings['OTHER_CFLAGS'] = flags + ['-Wno-deprecated-declarations', '-Wno-deprecated-implementations']
      end
    end
  end
end
